// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPydhAhOqf5d69qa5pKOthLuweo_wPRFA',
    appId: '1:668031586547:web:d328f210d1cddc35baa786',
    messagingSenderId: '668031586547',
    projectId: 'customermanager-5bd19',
    authDomain: 'customermanager-5bd19.firebaseapp.com',
    storageBucket: 'customermanager-5bd19.appspot.com',
    measurementId: 'G-WWN2H0MJLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb2vd57BgTTMQTpdJwL6-DxLEH_rA1Tkw',
    appId: '1:668031586547:android:2ce2f9835f265751baa786',
    messagingSenderId: '668031586547',
    projectId: 'customermanager-5bd19',
    storageBucket: 'customermanager-5bd19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3eUs3QXnMUHNEebHviSXpRiUFdFjyb1s',
    appId: '1:668031586547:ios:8cc54c8649dc4cb5baa786',
    messagingSenderId: '668031586547',
    projectId: 'customermanager-5bd19',
    storageBucket: 'customermanager-5bd19.appspot.com',
    iosClientId: '668031586547-22hmluu1870ues2c5qjvdphlnptp0p33.apps.googleusercontent.com',
    iosBundleId: 'com.nhom8.customerManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3eUs3QXnMUHNEebHviSXpRiUFdFjyb1s',
    appId: '1:668031586547:ios:8cc54c8649dc4cb5baa786',
    messagingSenderId: '668031586547',
    projectId: 'customermanager-5bd19',
    storageBucket: 'customermanager-5bd19.appspot.com',
    iosClientId: '668031586547-22hmluu1870ues2c5qjvdphlnptp0p33.apps.googleusercontent.com',
    iosBundleId: 'com.nhom8.customerManager',
  );
}
